# coding: utf-8

"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.394.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from plaid import schemas  # noqa: F401


class AssetTransactionCategoryType(
    schemas.EnumBase,
    schemas.StrBase,
    schemas.NoneBase,
    schemas.Schema,
    schemas.NoneStrMixin
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Asset Transaction Category Type Enumerated derived by Vendor.
    """


    class MetaOapg:
        enum_value_to_name = {
            "ATMFee": "ATMFEE",
            "Advertising": "ADVERTISING",
            "AirTravel": "AIR_TRAVEL",
            "AlcoholBars": "ALCOHOL_BARS",
            "Allowance": "ALLOWANCE",
            "Amusement": "AMUSEMENT",
            "Arts": "ARTS",
            "AutoTransport": "AUTO_TRANSPORT",
            "AutoInsurance": "AUTO_INSURANCE",
            "AutoPayment": "AUTO_PAYMENT",
            "BabySupplies": "BABY_SUPPLIES",
            "BabysitterDaycare": "BABYSITTER_DAYCARE",
            "BankFee": "BANK_FEE",
            "BillsUtilities": "BILLS_UTILITIES",
            "Bonus": "BONUS",
            "BooksSupplies": "BOOKS_SUPPLIES",
            "Business Services": "BUSINESS_SERVICES",
            "Buy": "BUY",
            "CashATM": "CASH_ATM",
            "Charity": "CHARITY",
            "Check": "CHECK",
            "ChildSupport": "CHILD_SUPPORT",
            "Clothing": "CLOTHING",
            "CoffeeShops": "COFFEE_SHOPS",
            "CreditCardPayment": "CREDIT_CARD_PAYMENT",
            "Dentist": "DENTIST",
            "Doctor": "DOCTOR",
            "Education": "EDUCATION",
            "ElectronicsSoftware": "ELECTRONICS_SOFTWARE",
            "Entertainment": "ENTERTAINMENT",
            "Eyecare": "EYECARE",
            "FastFood": "FAST_FOOD",
            "FederalTax": "FEDERAL_TAX",
            "FeesCharges": "FEES_CHARGES",
            "FinanceCharge": "FINANCE_CHARGE",
            "Financial": "FINANCIAL",
            "FinancialAdvisor": "FINANCIAL_ADVISOR",
            "FoodDining": "FOOD_DINING",
            "Furnishings": "FURNISHINGS",
            "GasFuel": "GAS_FUEL",
            "GiftsDonations": "GIFTS_DONATIONS",
            "Groceries": "GROCERIES",
            "Gym": "GYM",
            "Hair": "HAIR",
            "HealthFitness": "HEALTH_FITNESS",
            "HealthInsurance": "HEALTH_INSURANCE",
            "Hobbies": "HOBBIES",
            "Home": "HOME",
            "HomeImprovement": "HOME_IMPROVEMENT",
            "HomeInsurance": "HOME_INSURANCE",
            "HomePhone": "HOME_PHONE",
            "HomeServices": "HOME_SERVICES",
            "HomeSupplies": "HOME_SUPPLIES",
            "Hotel": "HOTEL",
            "Income": "INCOME",
            "InterestIncome": "INTEREST_INCOME",
            "Internet": "INTERNET",
            "Investments": "INVESTMENTS",
            "Kids": "KIDS",
            "KidsActivities": "KIDS_ACTIVITIES",
            "LateFee": "LATE_FEE",
            "Laundry": "LAUNDRY",
            "LawnGarden": "LAWN_GARDEN",
            "Legal": "LEGAL",
            "LifeInsurance": "LIFE_INSURANCE",
            "LoanInsurance": "LOAN_INSURANCE",
            "LoanPayment": "LOAN_PAYMENT",
            "Loans": "LOANS",
            "MobilePhone": "MOBILE_PHONE",
            "MortgageRent": "MORTGAGE_RENT",
            "MoviesDVDs": "MOVIES_DVDS",
            "Music": "MUSIC",
            "NewspapersMagazines": "NEWSPAPERS_MAGAZINES",
            "OfficeSupplies": "OFFICE_SUPPLIES",
            "Parking": "PARKING",
            "Paycheck": "PAYCHECK",
            "PersonalCare": "PERSONAL_CARE",
            "PetFoodSupplies": "PET_FOOD_SUPPLIES",
            "PetGrooming": "PET_GROOMING",
            "Pets": "PETS",
            "Pharmacy": "PHARMACY",
            "Printing": "PRINTING",
            "Property Tax": "PROPERTY_TAX",
            "Public Transportation": "PUBLIC_TRANSPORTATION",
            "Reimbursement": "REIMBURSEMENT",
            "RentalCarTaxi": "RENTAL_CAR_TAXI",
            "Restaurants": "RESTAURANTS",
            "SalesTax": "SALES_TAX",
            "ServiceParts": "SERVICE_PARTS",
            "ServiceFee": "SERVICE_FEE",
            "Shipping": "SHIPPING",
            "Shopping": "SHOPPING",
            "SpaMassage": "SPA_MASSAGE",
            "SportingGoods": "SPORTING_GOODS",
            "Sports": "SPORTS",
            "StateTax": "STATE_TAX",
            "Student Loan": "STUDENT_LOAN",
            "Taxes": "TAXES",
            "Television": "TELEVISION",
            "Toys": "TOYS",
            "Transfer": "TRANSFER",
            "Travel": "TRAVEL",
            "Tuition": "TUITION",
            "Uncategorized": "UNCATEGORIZED",
            "Utilities": "UTILITIES",
            "Vacation": "VACATION",
            "Veterinary": "VETERINARY",
        }
    
    @schemas.classproperty
    def ATMFEE(cls):
        return cls("ATMFee")
    
    @schemas.classproperty
    def ADVERTISING(cls):
        return cls("Advertising")
    
    @schemas.classproperty
    def AIR_TRAVEL(cls):
        return cls("AirTravel")
    
    @schemas.classproperty
    def ALCOHOL_BARS(cls):
        return cls("AlcoholBars")
    
    @schemas.classproperty
    def ALLOWANCE(cls):
        return cls("Allowance")
    
    @schemas.classproperty
    def AMUSEMENT(cls):
        return cls("Amusement")
    
    @schemas.classproperty
    def ARTS(cls):
        return cls("Arts")
    
    @schemas.classproperty
    def AUTO_TRANSPORT(cls):
        return cls("AutoTransport")
    
    @schemas.classproperty
    def AUTO_INSURANCE(cls):
        return cls("AutoInsurance")
    
    @schemas.classproperty
    def AUTO_PAYMENT(cls):
        return cls("AutoPayment")
    
    @schemas.classproperty
    def BABY_SUPPLIES(cls):
        return cls("BabySupplies")
    
    @schemas.classproperty
    def BABYSITTER_DAYCARE(cls):
        return cls("BabysitterDaycare")
    
    @schemas.classproperty
    def BANK_FEE(cls):
        return cls("BankFee")
    
    @schemas.classproperty
    def BILLS_UTILITIES(cls):
        return cls("BillsUtilities")
    
    @schemas.classproperty
    def BONUS(cls):
        return cls("Bonus")
    
    @schemas.classproperty
    def BOOKS_SUPPLIES(cls):
        return cls("BooksSupplies")
    
    @schemas.classproperty
    def BUSINESS_SERVICES(cls):
        return cls("Business Services")
    
    @schemas.classproperty
    def BUY(cls):
        return cls("Buy")
    
    @schemas.classproperty
    def CASH_ATM(cls):
        return cls("CashATM")
    
    @schemas.classproperty
    def CHARITY(cls):
        return cls("Charity")
    
    @schemas.classproperty
    def CHECK(cls):
        return cls("Check")
    
    @schemas.classproperty
    def CHILD_SUPPORT(cls):
        return cls("ChildSupport")
    
    @schemas.classproperty
    def CLOTHING(cls):
        return cls("Clothing")
    
    @schemas.classproperty
    def COFFEE_SHOPS(cls):
        return cls("CoffeeShops")
    
    @schemas.classproperty
    def CREDIT_CARD_PAYMENT(cls):
        return cls("CreditCardPayment")
    
    @schemas.classproperty
    def DENTIST(cls):
        return cls("Dentist")
    
    @schemas.classproperty
    def DOCTOR(cls):
        return cls("Doctor")
    
    @schemas.classproperty
    def EDUCATION(cls):
        return cls("Education")
    
    @schemas.classproperty
    def ELECTRONICS_SOFTWARE(cls):
        return cls("ElectronicsSoftware")
    
    @schemas.classproperty
    def ENTERTAINMENT(cls):
        return cls("Entertainment")
    
    @schemas.classproperty
    def EYECARE(cls):
        return cls("Eyecare")
    
    @schemas.classproperty
    def FAST_FOOD(cls):
        return cls("FastFood")
    
    @schemas.classproperty
    def FEDERAL_TAX(cls):
        return cls("FederalTax")
    
    @schemas.classproperty
    def FEES_CHARGES(cls):
        return cls("FeesCharges")
    
    @schemas.classproperty
    def FINANCE_CHARGE(cls):
        return cls("FinanceCharge")
    
    @schemas.classproperty
    def FINANCIAL(cls):
        return cls("Financial")
    
    @schemas.classproperty
    def FINANCIAL_ADVISOR(cls):
        return cls("FinancialAdvisor")
    
    @schemas.classproperty
    def FOOD_DINING(cls):
        return cls("FoodDining")
    
    @schemas.classproperty
    def FURNISHINGS(cls):
        return cls("Furnishings")
    
    @schemas.classproperty
    def GAS_FUEL(cls):
        return cls("GasFuel")
    
    @schemas.classproperty
    def GIFTS_DONATIONS(cls):
        return cls("GiftsDonations")
    
    @schemas.classproperty
    def GROCERIES(cls):
        return cls("Groceries")
    
    @schemas.classproperty
    def GYM(cls):
        return cls("Gym")
    
    @schemas.classproperty
    def HAIR(cls):
        return cls("Hair")
    
    @schemas.classproperty
    def HEALTH_FITNESS(cls):
        return cls("HealthFitness")
    
    @schemas.classproperty
    def HEALTH_INSURANCE(cls):
        return cls("HealthInsurance")
    
    @schemas.classproperty
    def HOBBIES(cls):
        return cls("Hobbies")
    
    @schemas.classproperty
    def HOME(cls):
        return cls("Home")
    
    @schemas.classproperty
    def HOME_IMPROVEMENT(cls):
        return cls("HomeImprovement")
    
    @schemas.classproperty
    def HOME_INSURANCE(cls):
        return cls("HomeInsurance")
    
    @schemas.classproperty
    def HOME_PHONE(cls):
        return cls("HomePhone")
    
    @schemas.classproperty
    def HOME_SERVICES(cls):
        return cls("HomeServices")
    
    @schemas.classproperty
    def HOME_SUPPLIES(cls):
        return cls("HomeSupplies")
    
    @schemas.classproperty
    def HOTEL(cls):
        return cls("Hotel")
    
    @schemas.classproperty
    def INCOME(cls):
        return cls("Income")
    
    @schemas.classproperty
    def INTEREST_INCOME(cls):
        return cls("InterestIncome")
    
    @schemas.classproperty
    def INTERNET(cls):
        return cls("Internet")
    
    @schemas.classproperty
    def INVESTMENTS(cls):
        return cls("Investments")
    
    @schemas.classproperty
    def KIDS(cls):
        return cls("Kids")
    
    @schemas.classproperty
    def KIDS_ACTIVITIES(cls):
        return cls("KidsActivities")
    
    @schemas.classproperty
    def LATE_FEE(cls):
        return cls("LateFee")
    
    @schemas.classproperty
    def LAUNDRY(cls):
        return cls("Laundry")
    
    @schemas.classproperty
    def LAWN_GARDEN(cls):
        return cls("LawnGarden")
    
    @schemas.classproperty
    def LEGAL(cls):
        return cls("Legal")
    
    @schemas.classproperty
    def LIFE_INSURANCE(cls):
        return cls("LifeInsurance")
    
    @schemas.classproperty
    def LOAN_INSURANCE(cls):
        return cls("LoanInsurance")
    
    @schemas.classproperty
    def LOAN_PAYMENT(cls):
        return cls("LoanPayment")
    
    @schemas.classproperty
    def LOANS(cls):
        return cls("Loans")
    
    @schemas.classproperty
    def MOBILE_PHONE(cls):
        return cls("MobilePhone")
    
    @schemas.classproperty
    def MORTGAGE_RENT(cls):
        return cls("MortgageRent")
    
    @schemas.classproperty
    def MOVIES_DVDS(cls):
        return cls("MoviesDVDs")
    
    @schemas.classproperty
    def MUSIC(cls):
        return cls("Music")
    
    @schemas.classproperty
    def NEWSPAPERS_MAGAZINES(cls):
        return cls("NewspapersMagazines")
    
    @schemas.classproperty
    def OFFICE_SUPPLIES(cls):
        return cls("OfficeSupplies")
    
    @schemas.classproperty
    def PARKING(cls):
        return cls("Parking")
    
    @schemas.classproperty
    def PAYCHECK(cls):
        return cls("Paycheck")
    
    @schemas.classproperty
    def PERSONAL_CARE(cls):
        return cls("PersonalCare")
    
    @schemas.classproperty
    def PET_FOOD_SUPPLIES(cls):
        return cls("PetFoodSupplies")
    
    @schemas.classproperty
    def PET_GROOMING(cls):
        return cls("PetGrooming")
    
    @schemas.classproperty
    def PETS(cls):
        return cls("Pets")
    
    @schemas.classproperty
    def PHARMACY(cls):
        return cls("Pharmacy")
    
    @schemas.classproperty
    def PRINTING(cls):
        return cls("Printing")
    
    @schemas.classproperty
    def PROPERTY_TAX(cls):
        return cls("Property Tax")
    
    @schemas.classproperty
    def PUBLIC_TRANSPORTATION(cls):
        return cls("Public Transportation")
    
    @schemas.classproperty
    def REIMBURSEMENT(cls):
        return cls("Reimbursement")
    
    @schemas.classproperty
    def RENTAL_CAR_TAXI(cls):
        return cls("RentalCarTaxi")
    
    @schemas.classproperty
    def RESTAURANTS(cls):
        return cls("Restaurants")
    
    @schemas.classproperty
    def SALES_TAX(cls):
        return cls("SalesTax")
    
    @schemas.classproperty
    def SERVICE_PARTS(cls):
        return cls("ServiceParts")
    
    @schemas.classproperty
    def SERVICE_FEE(cls):
        return cls("ServiceFee")
    
    @schemas.classproperty
    def SHIPPING(cls):
        return cls("Shipping")
    
    @schemas.classproperty
    def SHOPPING(cls):
        return cls("Shopping")
    
    @schemas.classproperty
    def SPA_MASSAGE(cls):
        return cls("SpaMassage")
    
    @schemas.classproperty
    def SPORTING_GOODS(cls):
        return cls("SportingGoods")
    
    @schemas.classproperty
    def SPORTS(cls):
        return cls("Sports")
    
    @schemas.classproperty
    def STATE_TAX(cls):
        return cls("StateTax")
    
    @schemas.classproperty
    def STUDENT_LOAN(cls):
        return cls("Student Loan")
    
    @schemas.classproperty
    def TAXES(cls):
        return cls("Taxes")
    
    @schemas.classproperty
    def TELEVISION(cls):
        return cls("Television")
    
    @schemas.classproperty
    def TOYS(cls):
        return cls("Toys")
    
    @schemas.classproperty
    def TRANSFER(cls):
        return cls("Transfer")
    
    @schemas.classproperty
    def TRAVEL(cls):
        return cls("Travel")
    
    @schemas.classproperty
    def TUITION(cls):
        return cls("Tuition")
    
    @schemas.classproperty
    def UNCATEGORIZED(cls):
        return cls("Uncategorized")
    
    @schemas.classproperty
    def UTILITIES(cls):
        return cls("Utilities")
    
    @schemas.classproperty
    def VACATION(cls):
        return cls("Vacation")
    
    @schemas.classproperty
    def VETERINARY(cls):
        return cls("Veterinary")


    def __new__(
        cls,
        *_args: typing.Union[None, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'AssetTransactionCategoryType':
        return super().__new__(
            cls,
            *_args,
            _configuration=_configuration,
        )
