# coding: utf-8

"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.394.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from plaid import schemas  # noqa: F401


class BankTransferBalance(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Information about the balance of a bank transfer
    """


    class MetaOapg:
        required = {
            "transactable",
            "available",
        }
        
        class properties:
            available = schemas.StrSchema
            transactable = schemas.StrSchema
            __annotations__ = {
                "available": available,
                "transactable": transactable,
            }
        additional_properties = schemas.AnyTypeSchema
    
    transactable: MetaOapg.properties.transactable
    available: MetaOapg.properties.available
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transactable"]) -> MetaOapg.properties.transactable: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["available"]) -> MetaOapg.properties.available: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> MetaOapg.additional_properties: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["transactable"], typing_extensions.Literal["available"], str, ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transactable"]) -> MetaOapg.properties.transactable: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["available"]) -> MetaOapg.properties.available: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[MetaOapg.additional_properties, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["transactable"], typing_extensions.Literal["available"], str, ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        transactable: typing.Union[MetaOapg.properties.transactable, str, ],
        available: typing.Union[MetaOapg.properties.available, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
    ) -> 'BankTransferBalance':
        return super().__new__(
            cls,
            *_args,
            transactable=transactable,
            available=available,
            _configuration=_configuration,
            **kwargs,
        )
