# coding: utf-8

"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.394.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from plaid import schemas  # noqa: F401


class CreditBankIncomeCause(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    An error object and associated `item_id` used to identify a specific Item and error when a batch operation operating on multiple Items has encountered an error in one of the Items.
    """


    class MetaOapg:
        required = {
            "error_message",
            "item_id",
            "error_type",
            "display_message",
            "error_code",
        }
        
        class properties:
        
            @staticmethod
            def error_type() -> typing.Type['CreditBankIncomeErrorType']:
                return CreditBankIncomeErrorType
            error_code = schemas.StrSchema
            error_message = schemas.StrSchema
            display_message = schemas.StrSchema
            item_id = schemas.StrSchema
            __annotations__ = {
                "error_type": error_type,
                "error_code": error_code,
                "error_message": error_message,
                "display_message": display_message,
                "item_id": item_id,
            }
    
    error_message: MetaOapg.properties.error_message
    item_id: MetaOapg.properties.item_id
    error_type: 'CreditBankIncomeErrorType'
    display_message: MetaOapg.properties.display_message
    error_code: MetaOapg.properties.error_code
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["error_type"]) -> 'CreditBankIncomeErrorType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["error_code"]) -> MetaOapg.properties.error_code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["error_message"]) -> MetaOapg.properties.error_message: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["display_message"]) -> MetaOapg.properties.display_message: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["item_id"]) -> MetaOapg.properties.item_id: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["error_type", "error_code", "error_message", "display_message", "item_id", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["error_type"]) -> 'CreditBankIncomeErrorType': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["error_code"]) -> MetaOapg.properties.error_code: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["error_message"]) -> MetaOapg.properties.error_message: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["display_message"]) -> MetaOapg.properties.display_message: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["item_id"]) -> MetaOapg.properties.item_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["error_type", "error_code", "error_message", "display_message", "item_id", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        error_message: typing.Union[MetaOapg.properties.error_message, str, ],
        item_id: typing.Union[MetaOapg.properties.item_id, str, ],
        error_type: 'CreditBankIncomeErrorType',
        display_message: typing.Union[MetaOapg.properties.display_message, str, ],
        error_code: typing.Union[MetaOapg.properties.error_code, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CreditBankIncomeCause':
        return super().__new__(
            cls,
            *_args,
            error_message=error_message,
            item_id=item_id,
            error_type=error_type,
            display_message=display_message,
            error_code=error_code,
            _configuration=_configuration,
            **kwargs,
        )

from plaid.model.credit_bank_income_error_type import CreditBankIncomeErrorType
