# coding: utf-8

"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.394.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from plaid import schemas  # noqa: F401


class InstitutionSupportedNetworks(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Contains the RTP network and types supported by the linked Item's institution.
    """


    class MetaOapg:
        required = {
            "rtp",
        }
        
        class properties:
        
            @staticmethod
            def rtp() -> typing.Type['TransferCapabilitiesGetRTP']:
                return TransferCapabilitiesGetRTP
            __annotations__ = {
                "rtp": rtp,
            }
        additional_properties = schemas.AnyTypeSchema
    
    rtp: 'TransferCapabilitiesGetRTP'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rtp"]) -> 'TransferCapabilitiesGetRTP': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> MetaOapg.additional_properties: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["rtp"], str, ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rtp"]) -> 'TransferCapabilitiesGetRTP': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[MetaOapg.additional_properties, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["rtp"], str, ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        rtp: 'TransferCapabilitiesGetRTP',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
    ) -> 'InstitutionSupportedNetworks':
        return super().__new__(
            cls,
            *_args,
            rtp=rtp,
            _configuration=_configuration,
            **kwargs,
        )

from plaid.model.transfer_capabilities_get_rtp import TransferCapabilitiesGetRTP
