# coding: utf-8

"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.394.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from plaid import schemas  # noqa: F401


class ValidationSources(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
    """


    class MetaOapg:
        required = {
            "VALIDATION_SOURCE",
        }
        
        class properties:
            
            
            class VALIDATION_SOURCE(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ValidationSource']:
                        return ValidationSource
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['ValidationSource'], typing.List['ValidationSource']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'VALIDATION_SOURCE':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ValidationSource':
                    return super().__getitem__(i)
            __annotations__ = {
                "VALIDATION_SOURCE": VALIDATION_SOURCE,
            }
        additional_properties = schemas.AnyTypeSchema
    
    VALIDATION_SOURCE: MetaOapg.properties.VALIDATION_SOURCE
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["VALIDATION_SOURCE"]) -> MetaOapg.properties.VALIDATION_SOURCE: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> MetaOapg.additional_properties: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["VALIDATION_SOURCE"], str, ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["VALIDATION_SOURCE"]) -> MetaOapg.properties.VALIDATION_SOURCE: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[MetaOapg.additional_properties, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["VALIDATION_SOURCE"], str, ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        VALIDATION_SOURCE: typing.Union[MetaOapg.properties.VALIDATION_SOURCE, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
    ) -> 'ValidationSources':
        return super().__new__(
            cls,
            *_args,
            VALIDATION_SOURCE=VALIDATION_SOURCE,
            _configuration=_configuration,
            **kwargs,
        )

from plaid.model.validation_source import ValidationSource
